version: "2"

services:
  simple-react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-react
    entrypoint: sh entrypoint.sh
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - "db:database"
  db:
    image: mariadb
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqladmin